### ISSUE TITLE
Language file syntax error

### ISSUE THREAD

**Issue by gade01** [xbmc/audiodecoder.2sf#23]
When trying to add this add-on to our Weblate translation project, I encountered a syntax error in the German translation:

https://github.com/xbmc/audiodecoder.2sf/blob/Matrix/audiodecoder.2sf/resources/language/resource.language.de_de/strings.po#L89

`msgid` should be `msgstr`

**Comment by AlwinEsch** [comment]
Has brought your fix in, will also create a new release then to have available.

**Comment by gade01** [comment]
Great, thanks.

I'll add it to our demo Weblate project.
